### ISSUE TITLE
Use SWC over Deno

### ISSUE THREAD

**Issue by nicolad** [paritytech/useink#35]
### Suggestion

To make contributing to the useink project easier, I suggest switching from Deno to [SWC](https://swc.rs/) for code transformation.

### Motivation

Currently, useink uses Deno for code transformation. However, Deno is a relatively new technology and has a smaller user base compared to SWC. This makes it harder for contributors to the project who are not familiar with Deno to get started.

On the other hand, SWC has been gaining popularity and has a larger user base. It also has better compatibility with existing tools and frameworks in the JavaScript ecosystem. This would make it easier for developers to contribute to the useink project.

### Use Cases

By switching to SWC, developers can use the tools and frameworks they are already familiar with, making it easier for them to contribute to the project. This would help grow the contributor base of the project and increase the pace of development.

**Comment by nicolad** [comment]
what do you think @DoubleOTheven ?

**Comment by nicolad** [comment]
or vite

**Comment by DoubleOTheven** [comment]
@nicolad This is a good suggestion. It has come up before. 

The reason we decided to go with Deno was because [Capi](github.com/paritytech/capi) is built with Deno and we plan to use that in the future. We thought it was best to encourage those developers.

We have a ink! team retreat April 10-14. We will discuss it a bit more. We can also keep chatting here in this thread.

If we do choose to keep Deno then I will need to create some documentation on setting it up. It is easy once you get past the initial learning curve, but this may be a blocker to new developers. Thanks for bringing this up

**Comment by nicolad** [comment]
Thanks @DoubleOTheven for the response.
Wondering if it would be possible to enable `discussions` section, such that I won't add too much noise to the issue section, since this isn't an "issue" per se.
